version: '3.8'

services:
  sw2p2-backend:
    build: .
    ports:
      - "9191:9191"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://grupo01:d5QGObx1tXkW07u3@sw2p2backend.hahdn3u.mongodb.net/med_db?retryWrites=true&w=majority&appName=sw2p2backend
    restart: unless-stopped

